### ISSUE TITLE
I cannot export protobuf of Caffe2 model with types and shapes.

### ISSUE THREAD

**Issue by Haoran-Young** [facebookresearch/dlrm#104]
I add "--save-proto-tyes-shapes" into the dlrm_s_criteo_kaggle.sh to save the trained model.
But I cannot save the trained Caffe2 model successfully.

Here is the Traceback information:
=============================================================
Finished training it 294912/306968 of epoch 0, 17.40 ms/it, loss 0.446618, accuracy 79.198 %
Finished training it 295936/306968 of epoch 0, 17.02 ms/it, loss 0.446991, accuracy 79.222 %
Finished training it 296960/306968 of epoch 0, 16.92 ms/it, loss 0.447681, accuracy 79.198 %
Finished training it 297984/306968 of epoch 0, 17.49 ms/it, loss 0.450688, accuracy 78.951 %
Finished training it 299008/306968 of epoch 0, 17.00 ms/it, loss 0.449784, accuracy 79.047 %
Finished training it 300032/306968 of epoch 0, 16.93 ms/it, loss 0.446797, accuracy 79.252 %
Finished training it 301056/306968 of epoch 0, 16.95 ms/it, loss 0.446337, accuracy 79.275 %
Finished training it 302080/306968 of epoch 0, 26.41 ms/it, loss 0.446247, accuracy 79.202 %
Finished training it 303104/306968 of epoch 0, 22.36 ms/it, loss 0.447592, accuracy 79.124 %
Finished training it 304128/306968 of epoch 0, 16.83 ms/it, loss 0.448061, accuracy 79.115 %
Finished training it 305152/306968 of epoch 0, 16.79 ms/it, loss 0.445043, accuracy 79.235 %
Finished training it 306176/306968 of epoch 0, 16.81 ms/it, loss 0.446699, accuracy 79.343 %
Finished training it 306968/306968 of epoch 0, 17.41 ms/it, loss 0.448240, accuracy 79.227 %
Traceback (most recent call last):
  File "dlrm_s_caffe2.py", line 1331, in <module>
    t = arg.tensors.add()
AttributeError: tensors
done
===============================================================

I want to have a *.pb file to draw the DLRM structure via Netron. The saving function you provided (line 1347 -line 1354) exports two files (init_net and predict_net), but both of them cannot be plotted by Netron (I have changed two files type into *.pb, still does not work)

**Comment by mnaumovfb** [comment]
I believe that there are two separate questions above: (i) about exporting protobuf and (ii) regarding Netron tool.

(i) I can not reproduce your errors in exporting the protobuf. However, there was indeed a minor bug in the code, which I have fixed with the following [commit](https://github.com/facebookresearch/dlrm/commit/21d00785a3b964973e5642ead112b55492157372). After this change, I can export protofbuf with types and shapes, [as well as weights](https://github.com/facebookresearch/dlrm/blob/master/dlrm_s_caffe2.py#L1310).

(ii) We do not currently support Netron tool, therefore I do not know what are the requirements and whether the exported model will work with it.

**Comment by Haoran-Young** [comment]
Thanks for your response.
It is bizarre that I did not make any modifications to your code, but the problem happened. The processes of training and testing work well, it just cannot export protobuf.
As to Netron, you are right, and there are some issues for it to support Caffe2.
The Pytorch version of DLRM can run successfully, so I am now trying to use the Pytorch version.

**Comment by mnaumovfb** [comment]
Are you able to export the protobuf with types and shapes now (or do you still see the same problem)?

**Comment by Haoran-Young** [comment]
No......still the same problem.

According to your commit, it seems that you are trying to fix functions about saving ONNX model. But the comments in your code said (line 1295 - line 1298):
'''
WARNING: Why Caffe2 to ONNX net transformation currently does not work?
ONNX does not support SparseLengthsSum operator directly. A workaround
could be for the Caffe2 ONNX frontend to indirectly map this operator to
Gather and ReducedSum ONNX operators, following the PyTorch approach.
'''
And, indeed, saving ONNX model did not work in Caffe2 version of your model as the comments said. So, I did not use '--save-onnx' to run the code at all.

What I used to export protobuf with types and shapes was using '--save-proto-types-shapes' (line 1308 - line 1342).

**Comment by mnaumovfb** [comment]
Let me clarify that exporting ONNX and protobuf are two different things. 

The former will not work as explained in the comments you have cited above. The latter should work with the latest version of the code. Are you using the latest PyTorch/Caffe2 nightly version of the frameworks? what about Python version?

**Comment by Haoran-Young** [comment]
Hi @mnaumovfb, thanks for your reminds.
I have solved this problem by updating the PyTorch/Caffe2 versions.
I recommend that you should specify the versions of dependencies in the 'requirements.txt' so that other users can avoid these kinds of problems.

What's more, this is an extraordinary project, thanks for your efforts.
